/* The sound, pulled in whole (generated by tools/audio/make_audio.py). */
    .section .rodata.snd_lobby,"a"
    .global snd_lobby
    .balign 4
snd_lobby:
    .incbin "audio/lobby.bin"
    .section .rodata.snd_game,"a"
    .global snd_game
    .balign 4
snd_game:
    .incbin "audio/game.bin"
    .section .rodata.snd_win,"a"
    .global snd_win
    .balign 4
snd_win:
    .incbin "audio/win.bin"
    .section .rodata.snd_lose,"a"
    .global snd_lose
    .balign 4
snd_lose:
    .incbin "audio/lose.bin"
    .section .rodata.snd_sfx_move,"a"
    .global snd_sfx_move
    .balign 4
snd_sfx_move:
    .incbin "audio/sfx_move.bin"
    .section .rodata.snd_sfx_select,"a"
    .global snd_sfx_select
    .balign 4
snd_sfx_select:
    .incbin "audio/sfx_select.bin"
    .section .rodata.snd_sfx_back,"a"
    .global snd_sfx_back
    .balign 4
snd_sfx_back:
    .incbin "audio/sfx_back.bin"
    .section .rodata.snd_sfx_place,"a"
    .global snd_sfx_place
    .balign 4
snd_sfx_place:
    .incbin "audio/sfx_place.bin"
    .section .rodata.snd_sfx_capture,"a"
    .global snd_sfx_capture
    .balign 4
snd_sfx_capture:
    .incbin "audio/sfx_capture.bin"
    .section .rodata.snd_sfx_turn,"a"
    .global snd_sfx_turn
    .balign 4
snd_sfx_turn:
    .incbin "audio/sfx_turn.bin"
    .section .rodata.snd_sfx_error,"a"
    .global snd_sfx_error
    .balign 4
snd_sfx_error:
    .incbin "audio/sfx_error.bin"
    .section .rodata.snd_sfx_start,"a"
    .global snd_sfx_start
    .balign 4
snd_sfx_start:
    .incbin "audio/sfx_start.bin"
