// Generated by tools/audio/make_audio.py: do not edit.
#ifndef SNC_AUDIO_H
#define SNC_AUDIO_H
#include <stdint.h>

extern const uint8_t snd_lobby[];  // 16-bit PCM
#define SND_LOBBY_BYTES 1875976
#define SND_LOBBY_RATE 22050
#define SND_LOBBY_SAMPLES 937988
extern const uint8_t snd_game[];  // 16-bit PCM
#define SND_GAME_BYTES 2190396
#define SND_GAME_RATE 22050
#define SND_GAME_SAMPLES 1095198
extern const uint8_t snd_win[];  // 16-bit PCM
#define SND_WIN_BYTES 245668
#define SND_WIN_RATE 22050
#define SND_WIN_SAMPLES 122834
extern const uint8_t snd_lose[];  // 16-bit PCM
#define SND_LOSE_BYTES 205432
#define SND_LOSE_RATE 22050
#define SND_LOSE_SAMPLES 102716
extern const uint8_t snd_sfx_move[];  // 16-bit PCM
#define SND_SFX_MOVE_BYTES 21168
#define SND_SFX_MOVE_RATE 22050
#define SND_SFX_MOVE_SAMPLES 10584
extern const uint8_t snd_sfx_select[];  // 16-bit PCM
#define SND_SFX_SELECT_BYTES 26460
#define SND_SFX_SELECT_RATE 22050
#define SND_SFX_SELECT_SAMPLES 13230
extern const uint8_t snd_sfx_back[];  // 16-bit PCM
#define SND_SFX_BACK_BYTES 21168
#define SND_SFX_BACK_RATE 22050
#define SND_SFX_BACK_SAMPLES 10584
extern const uint8_t snd_sfx_place[];  // 16-bit PCM
#define SND_SFX_PLACE_BYTES 26460
#define SND_SFX_PLACE_RATE 22050
#define SND_SFX_PLACE_SAMPLES 13230
extern const uint8_t snd_sfx_capture[];  // 16-bit PCM
#define SND_SFX_CAPTURE_BYTES 32176
#define SND_SFX_CAPTURE_RATE 22050
#define SND_SFX_CAPTURE_SAMPLES 16088
extern const uint8_t snd_sfx_turn[];  // 16-bit PCM
#define SND_SFX_TURN_BYTES 35280
#define SND_SFX_TURN_RATE 22050
#define SND_SFX_TURN_SAMPLES 17640
extern const uint8_t snd_sfx_error[];  // 16-bit PCM
#define SND_SFX_ERROR_BYTES 21168
#define SND_SFX_ERROR_RATE 22050
#define SND_SFX_ERROR_SAMPLES 10584
extern const uint8_t snd_sfx_start[];  // 16-bit PCM
#define SND_SFX_START_BYTES 52920
#define SND_SFX_START_RATE 22050
#define SND_SFX_START_SAMPLES 26460

#endif
