// Writes core/snc_certs.h from tools/roots.pem (the Let's Encrypt roots the API host chains to).
// Run it again if the roots ever change: node tools/make_certs.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const lines = readFileSync(new URL('./roots.pem', import.meta.url), 'utf8')
	.replace(/\r/g, '')
	.split('\n')
	.filter((l) => l.trim());

let out = "// The roots the API host chains to: Let's Encrypt's ISRG Root X1 and X2 and its\n";
out += '// generation-Y roots YR and YE (https://letsencrypt.org/certificates/).\n';
out += '// Public certificates. mbedtls_x509_crt_parse() takes the whole string, NUL included.\n';
out += '// Generated by tools/make_certs.mjs from tools/roots.pem.\n';
out += '#ifndef SNC_CERTS_H\n#define SNC_CERTS_H\nstatic const char SNC_ROOT_CERTS[] =\n';
for (const l of lines) out += '    "' + l + '\\n"\n';
out += '    ;\n#endif\n';
writeFileSync(new URL('../core/snc_certs.h', import.meta.url), out);
